name: skills_ez
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.5 <4.0.0"

dependencies:
  jaspr: ^0.22.0
  jaspr_router: ^0.8.1
  http: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0
  lints: ^6.0.0

jaspr:
  mode: server
  flutter: plugins
