name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  shared:
    path: ../shared
  http: ^1.2.1
  dotenv: ^4.0.1
  mysql1: ^0.20.0

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
